### ISSUE TITLE
Ability to cancel running workflows

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#10]

**Comment by roseDickinson** [comment]
This has a feature associated with it in our backlog [CORE-294](https://jira.dafni.rl.ac.uk/browse/CORE-294) (DAFNI internal link) it would be good to get an idea of how valuable this feature is to you so we can prioritise it more accurately.

**Comment by fmcclean** [comment]
It would be useful if a simulation is taking much longer than expected to complete although not essential. It may also happen that a mistake in the workflow is identified after an instance has started.

**Comment by roseDickinson** [comment]
This was added in February 2024
