### ISSUE TITLE
Version message should be added last when editing a workflow

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#102]
At the moment, the version message needs to be defined before making any changes to a workflow. It would make more sense to be able to create a message after making the changes because a user may not know in advance all of the changes they are going to make.

**Comment by fmcclean** [comment]
The same issue applies to parameter set names and descriptions, ideally, all of the metadata for workflows and parameter sets should be editable on the same page as the parameters and steps themselves. This way, the descriptions/version messages could be updated to reflect changes as they are made.

**Comment by roseDickinson** [comment]
This was fixed in v4.0.0
