### ISSUE TITLE
Warning message incorrect when deleting dataset version

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#103]
The warning says `Do you really want to delete dataset version <dataset_name>?` when it should say  `Do you really want to delete dataset version <dataset_version_name>?`

**Comment by tg137** [comment]
Well spotted, thanks.

Have made an internal ticket: https://jira.dafni.rl.ac.uk/browse/CORE-2154

**Comment by roseDickinson** [comment]
This was fixed in v3.2.0
