### ISSUE TITLE
Add some pre-run validation for running a workflow version with a parameter set

### ISSUE THREAD

**Issue by tg137** [dafnifacility/user-feedback#105]
When a new version of a workflow is created, it is not guaranteed that existing parameter sets will work with that new workflow version. This means that users can run workflows that aren't valid.

It would be good to have some validation on a workflow version / parameter set combination before the workflow is executed. Any problems would then be displayed to the user.

As reported by Fergus, chat attached. 
![image](https://user-images.githubusercontent.com/14982322/140527592-dc3edab2-ecf3-471e-8d3e-77f7b4fea020.png)

**Comment by roseDickinson** [comment]
This will be released in v4.2.0 in the next couple of weeks
