### ISSUE TITLE
Adding a single space to a parameter set description allows you to continue to the next step but will ultimately fail to save

### ISSUE THREAD

**Issue by tg137** [dafnifacility/user-feedback#109]
The front end should do some validation here to make sure that the description field is not just " " to stop the user from continuing with an erroneous workflow. 

As reported by Fergus.
![image](https://user-images.githubusercontent.com/14982322/143007556-b3486df6-85b9-4aca-bcf0-3029655ea81a.png)

**Comment by roseDickinson** [comment]
This is no longer possible as of v4.0.0
