### ISSUE TITLE
Model name is incorrect on workflow status screen

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#12]
![image](https://user-images.githubusercontent.com/17356802/90908199-f797ac00-e3cb-11ea-876c-bf97f44f6b00.png)

**Comment by BethanPerkins** [comment]
Ticket created for this: [CORE-1355](https://jira.dafni.rl.ac.uk/browse/CORE-1355) (DAFNI internal only)

**Comment by BethanPerkins** [comment]
Ticket resolved in version release 1.11.0 (November 10, 2020)
