### ISSUE TITLE
Files are empty when opened from Jupyter notebook

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#14]

**Comment by BethanPerkins** [comment]
Ticket created: [CORE-1300](https://jira.dafni.rl.ac.uk/browse/CORE-1300) (DAFNI STFC internal only)

**Comment by Craig-Robson** [comment]
Would be good to see this bug resolved (noted it is marked as in-progress), will make the current visualisation options more flexable for developing outputs which can be shared.

**Comment by fmcclean** [comment]
To be clear, this bug means that the visualisation functionality is broken at the moment (unless I'm doing something wrong)

**Comment by tg137** [comment]
Hi both, this is now fixed and tested.
