### ISSUE TITLE
Add option to download all data files in single archive

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#18]

**Comment by BethanPerkins** [comment]
This has been under consideration for a while. Just to be clear, when you say 'single archive' - do you specifically want a zip file of all of them or something else?

**Comment by fmcclean** [comment]
Yes, a single zip or tar.gz would be good. Ideally you would be able to select a combination of files and then download these in a single archive but I appreciate that's more work to implement.

**Comment by BethanPerkins** [comment]
Captured in ticket [CORE-1440](https://jira.dafni.rl.ac.uk/browse/CORE-1440) (DAFNI internal)

**Comment by roseDickinson** [comment]
Added this in v4.1.0
