### ISSUE TITLE
Share workflows, models and datasets within user groups

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#20]

**Comment by roseDickinson** [comment]
I've added a comment here to explain the current situation with this feature https://github.com/dafnifacility/user-feedback/issues/28#issuecomment-694752954.

**Comment by tomalrussell** [comment]
Thanks for the note over on #28 @roseDickinson - this bundle of work will be very useful for collaborative development and non-public projects.

**Comment by Craig-Robson** [comment]
Great to see this is being addressed. As the number of users and projects using DAFNI increases having a self-administered permission update method will become more important and will make working of DAFNI easier.

**Comment by BethanPerkins** [comment]
Captured by DAFNI internal tickets [CORE-155](https://jira.dafni.rl.ac.uk/browse/CORE-155) and [CORE-156](https://jira.dafni.rl.ac.uk/browse/CORE-156)

**Comment by roseDickinson** [comment]
Workflows are shareable in groups as of v3.1.0
