### ISSUE TITLE
Visualise and publish steps are conflated

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#22]
There is an implicit publish step within the visualise step which is not obvious to the user. I suggest either renaming 'visualise' to 'visualise and publish' or removing the implicit publish step and requiring a separate publish step if a visualise step is added.

**Comment by roseDickinson** [comment]
This is a restriction of the current NIVS system we have in place. The upgrade to the NIVS should remove the implicit publish step within the visualise step, though it may come with the requirement that a visualise step be preceded by a publish step - this is yet to be decided I believe.

**Comment by BethanPerkins** [comment]
Rose is right, this is one to come back to once we have the new visualisation system in place. Request captured for now in [CORE-1446](https://jira.dafni.rl.ac.uk/browse/CORE-1446)

**Comment by roseDickinson** [comment]
For the time being we have now renamed visualisation steps to "visualise and publish" with the new Workflows system as of v4.0.0
