### ISSUE TITLE
'Use metadata file' option causes workflows to fail

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#23]
The status screen also does not show all steps when a metadata file is used.

**Comment by roseDickinson** [comment]
Thank you for reporting this bug. I've added a bug to our next Sprint to take a look at this [CORE-1357](https://jira.dafni.rl.ac.uk/browse/CORE-1357). (DAFNI internal link)

**Comment by fmcclean** [comment]
The status screen now shows everything but the visualisation step fails. Should this be working now or is it still in progress?

**Comment by fmcclean** [comment]
Are there any updates on this? Thanks

**Comment by BethanPerkins** [comment]
The ticket is showing as Done on our JIRA boards. Are you still seeing the problem?

**Comment by fmcclean** [comment]
Tested and currently failing. Tom is going to look into it.

**Comment by tg137** [comment]
This was fixed a while ago, I forgot to close it here.
