### ISSUE TITLE
It's not obvious how to rename a workflow

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#25]
I suggest having the form that appears when the far left circle is clicked be always shown above the workflow diagram when editing a workflow

**Comment by roseDickinson** [comment]
We have wireframed up an improvement to the Workflows pages that should make this more obvious - the idea being that we would separate out changing the Workflow metadata (like the name) from the tool designed to edit the Workflow's steps. The task that covers this work is [CORE-907](https://jira.dafni.rl.ac.uk/browse/CORE-907). (DAFNI internal link)

**Comment by tg137** [comment]
This is addressed in the 3.0.0 release.
