### ISSUE TITLE
Workflow diagram is not scrollable  

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#27]
This means that some content can be off-screen and unreachable

**Comment by roseDickinson** [comment]
Hi Fergus, if I am understanding your feedback correctly there is actually a way of panning around in the Workflow canvas, if you click, hold and drag in any of the white section around the Workflow it should pan around. If you accidentally pan too far and lose the Workflow you can press the "Reset position" button to reset it to have the Workflow centred in the canvas.

**Comment by fmcclean** [comment]
OK thanks, do you think it would be helpful to add some text telling the user that because it wasn't very obvious to me?

**Comment by roseDickinson** [comment]
Hi Fergus, sorry I should have got back to you earlier on this with an update. We agreed with you that some hint text would help users! I've released a hotfix this morning that adds the hint text:

![image](https://user-images.githubusercontent.com/47528557/95988844-61a75d00-0e21-11eb-9c3c-411d000704be.png)

Are you happy for me to mark this issue as closed?

**Comment by fmcclean** [comment]
Looks good to me, thanks!
