### ISSUE TITLE
Add workflows and models to 'Manage Assets'

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#28]
I am sharing workflows and models with other users and it would be nice to see who can access them.

**Comment by roseDickinson** [comment]
The Manage Assets page only allows you to change the visibility of assets with respect to the Public group on DAFNI. There is work on going to add Group Creation [CORE-155](https://jira.dafni.rl.ac.uk/browse/CORE-155) and Group Management [CORE-156](https://jira.dafni.rl.ac.uk/browse/CORE-156) that should hopefully provide a better user journey for sharing assets. There are complications around sharing Workflows and Models until we settle on a way of providing versioning for these Asset Types.

**Comment by BethanPerkins** [comment]
Workflow and Model versioning work mentioned by Rose is also discussed in https://github.com/dafnifacility/user-feedback/issues/9

**Comment by BethanPerkins** [comment]
Captured in DAFNI internal ticket [CORE-1449](https://jira.dafni.rl.ac.uk/browse/CORE-1449)

**Comment by BethanPerkins** [comment]
This ticket is partially met by release v1.16. It is now possible to share models through the Groups pages and to request that models are made public.

**Comment by roseDickinson** [comment]
Workflows are shareable in groups as of v3.1.0
