### ISSUE TITLE
'Published by' showing user ID rather than name on model screen

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#29]

**Comment by roseDickinson** [comment]
This should be handled once we upgrade our login system to Keycloak - the idea being that the user ID will be used to grab the name from Keycloak and displayed instead.

**Comment by BethanPerkins** [comment]
Captured in DAFNI internal ticket [CORE-1457](https://jira.dafni.rl.ac.uk/browse/CORE-1457)

**Comment by tg137** [comment]
This is addressed in the 3.0.0 release.
