### ISSUE TITLE
Data upload progress indicator

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#32]
This could reuse the model upload implementation

**Comment by BethanPerkins** [comment]
Hi Fergus - could I have a bit more background to this one please? Is this something that you've struggled without e.g. for a large dataset? If so, it would be great to know which dataset(s) this was.

**Comment by BethanPerkins** [comment]
Captured in Feature Request [CORE-1367](https://jira.dafni.rl.ac.uk/browse/CORE-1367) (DAFNI internal)

**Comment by fmcclean** [comment]
It's a low priority one but would be useful to be able to see that the data is still uploading if it's taking a while, and having a progress indicator would be more in line with model upload

**Comment by BethanPerkins** [comment]
Data upload has been updated to include a progress bar in v1.15. Closing ticket.
