### ISSUE TITLE
Page titles should reflect content

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#34]
At the moment all pages are called 'DAFNI Facility' and this can become confusing when navigating between browser tabs.

**Comment by BethanPerkins** [comment]
Thanks for the suggestion. Captured in Feature Request [CORE-1364](https://jira.dafni.rl.ac.uk/browse/CORE-1364) (DAFNI Internal)

**Comment by roseDickinson** [comment]
This was fixed and released as part of v2.4.0.
