### ISSUE TITLE
Parameter descriptions are never displayed to user

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#36]
These are specified in the model definition file but inaccessible from the UI. It would be helpful to see them maybe in a tooltip when the parameters are hovered over in a form or when clicking on a question mark.

**Comment by roseDickinson** [comment]
Hi Fergus, we did have the parameter descriptions available in a tooltip on the Model details page but it looks like that has stopped working at some point. I've created [CORE-1368](https://jira.dafni.rl.ac.uk/browse/CORE-1368) to track this, thanks for the spot!

**Comment by roseDickinson** [comment]
Hi Fergus, I released a hotfix this morning that fixes the tooltips and as a result allows you to see the description for parameters when you hover over the `i` icon. Are you happy for me to close this issue?

**Comment by fmcclean** [comment]
Thanks @roseDickinson - I can now see parameter descriptions on the model pages which is great. An additional place that this information would be useful is the parameters form when editing a workflow. If it's not too much trouble, it would be good to see them here as well.

**Comment by roseDickinson** [comment]
Hi Fergus, I agree it would be useful to have the tooltips there too, I've added a task to our backlog for that [CORE-1459](https://jira.dafni.rl.ac.uk/browse/CORE-1459).

**Comment by roseDickinson** [comment]
Parameter descriptions have been added to Model steps on the Workflow editing page and this was released in v1.14.0
