### ISSUE TITLE
[Bug] Can not retrieve result files in subdirectories

### ISSUE THREAD

**Issue by JusteRaimbault** [dafnifacility/user-feedback#42]
I had some result files produced in my container with an absolute path `/data/outputs/mysubdirectory/myresultfile.csv`; a simple workflow model -- visualization failed at the visualization step, either using `outputs/*`, `outputs/mysubdirectory/*`, `outputs/mysubdirectory/myresultfile.csv` as data files.
It was fixed by putting the files in `/data/outputs` only.

**Comment by akademy** [comment]
Hi. The file selection works in the same was as a Unix style pathname pattern expansion. This Python documentation has some good description of this: https://docs.python.org/3/library/glob.html

The statement `outputs/**/*` should select everything.

There also appears to be bug in the file selection that breaks the visualise step if no files are selected. We'll take a look into that.

Sorry the output mechanism isn't formally documented.

**Comment by BethanPerkins** [comment]
Captured in DAFNI internal ticket [CORE-1465](https://jira.dafni.rl.ac.uk/browse/CORE-1465)

**Comment by tg137** [comment]
We have added better documentation for this feature in v3.0.0 at the point of adding the dataset path.
