### ISSUE TITLE
[Enh] Add more flexibility in workflow editing

### ISSUE THREAD

**Issue by JusteRaimbault** [dafnifacility/user-feedback#43]
For now, when adding tasks in a workflow, the addition of a new task is necessarily after the last task inserted, by clicking on the `+` button. It would be useful to be able to insert anywhere.
Furthermore, it seems that workflows are only sequential (except for iterators) - could it be possible to have some parallel parts in workflows. For example, `model` requires data from two different pre-processing models `premodel1` and `premodel2` which are independent, then instead of doing `premodel1 -- premodel2 -- model` and having to pass all files through and not being able to parallel the two execution, it would be great to be able to do something like
```
premodel1 --|
            I-- model
premodel2 --|
``` 
and similarly in outputs of models.

**Comment by fmcclean** [comment]
I agree that this would be useful after some other higher priority features are added

**Comment by BethanPerkins** [comment]
Captured in DAFNI internal ticket [CORE-1463](https://jira.dafni.rl.ac.uk/browse/CORE-1463)

**Comment by roseDickinson** [comment]
This was always possible and happened automatically in our apis but it was not reflected in the Workflow builer UI. As of v4.0.0 you can now have these multi dependent steps and branches in your worklfows
