### ISSUE TITLE
[Bug] Model upload fails with a slow connection

### ISSUE THREAD

**Issue by JusteRaimbault** [dafnifacility/user-feedback#44]
When trying to upload a model with a very slow connection (takes more than one hour to upload the 500Mo compressed image, so upload speed is around 140k/s), the operation fails when reaching 100% - nothing happens and the page is stuck with the upload popup with both upload bars at 100% (see screenshot below).
<img width="1438" alt="dafni_upload_slow" src="https://user-images.githubusercontent.com/3902759/95874806-35c8a080-0d69-11eb-9f0a-d39ce46799d8.png">

**Comment by roseDickinson** [comment]
Hi Juste, this is probably because your login session expired during the upload. We are working on moving our login system over to Keycloak ([CORE-246](https://jira.dafni.rl.ac.uk/browse/CORE-246) internal link) which will keep your login session open while you are uploading among other benefits. I am surprised that an error wasn't shown when your session expired though, I'll add a bug to the backlog to raise this issue.

**Comment by JusteRaimbault** [comment]
Thanks for the answer! Looking forward for the new login system!
I suspected there may be problems with session expiring, so I had an other DAFNI tab opened during the upload and updated it regularly (but it still failed) - could keeping the session alive manually like this (for example loading a new DAFNI page in the other tab) during the upload fix temporarily the issue?
(I guess the option to pull from a docker hub will also be a workaround when it will be available)

**Comment by fmcclean** [comment]
I have also encountered being logged out and not notified

**Comment by JusteRaimbault** [comment]
Just to follow-up on this issue of being logged out - I had the same issue when trying to upload a large dataset - the upload never finished, and I had to relog when opening a new window.
Could it be possible to add a progress bar for data upload in a way similar to model upload?

**Comment by fmcclean** [comment]
>Could it be possible to add a progress bar for data upload in a way similar to model upload?

There is an open issue for this here: #32

**Comment by roseDickinson** [comment]
Keycloak was released as part of v2.4.0 earlier this year. Login sessions should refresh while you are uploading large datasets or models now.
