### ISSUE TITLE
Add model with no parameters to workflow

### ISSUE THREAD

**Issue by tomalrussell** [dafnifacility/user-feedback#46]
Testing with a hello-world container, which has no parameters ([model link](https://facility.secure.dafni.rl.ac.uk/models/hello-world-1e647c43-115b-4a87-bdb3-a9b4dec90c03))

The "Create Step" button remains disabled when trying to add this as a model step:

![Screenshot from 2020-10-15 11-09-02](https://user-images.githubusercontent.com/2762769/96109974-27989280-0ed7-11eb-9e1e-e7d3055e1d92.png)

**Comment by roseDickinson** [comment]
Hi Tom, Looking at that screenshot the step name is blank, which is probably why the Create Step button is still disabled. Can you try entering the step name and let us know if the problem persists!

**Comment by tomalrussell** [comment]
That'll do the trick! Thanks @roseDickinson - maybe add a big red box around missing things to help a fool in a hurry?

**Comment by fmcclean** [comment]
Linked to #33
