### ISSUE TITLE
Add Open Roads dataset on DAFNI

### ISSUE THREAD

**Issue by cristiangns** [dafnifacility/user-feedback#48]
The UK road network topology can be downloaded from here: https://www.ordnancesurvey.co.uk/business-government/products/open-map-roads
It would be nice to have this as a dataset available on DAFNI. Maybe you could also add a tool that allows you to extract part of the network.

**Comment by BethanPerkins** [comment]
Thanks very much Cristian. I've had a look and we do have a copy of this dataset: https://facility.secure.dafni.rl.ac.uk/data/details?dataset_id=d34c5213-e8a7-4107-9825-168f3abb08c7&version_id=2a266819-b8e6-4a05-995c-7b9d76789976&metadata_id=5f733fd6-3f35-4419-9617-356ffea528f2
(or search for 'Roads').

We're not able to subset it yet, but it would be useful to know a bit more about how you would use it.

**Comment by BethanPerkins** [comment]
Hi @cristiangns - let me know if there is anything more we can do here. Otherwise I'll close this ticket as resolved.
Cheers 
Bethan

**Comment by cristiangns** [comment]
You can close the ticket. Thanks
