### ISSUE TITLE
Switching pages when adding data to groups causes selection change

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#52]
![DAFNI Facility](https://user-images.githubusercontent.com/17356802/99084827-59c50f00-25bf-11eb-92d4-9c34dcdf5f6d.gif)

**Comment by tg137** [comment]
Hi Fergus, thanks for this, nice spot. 

I've added an internal bug for this [CORE-1527](https://jira.dafni.rl.ac.uk/browse/CORE-1527)

**Comment by BethanPerkins** [comment]
CORE-1527 released today, fixing this bug. Marking as closed.
