### ISSUE TITLE
United Kingdom spatial extent incorrect

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#53]
![image](https://user-images.githubusercontent.com/17356802/99819930-06673980-2b48-11eb-8454-5e25f07c4b6f.png)

**Comment by tg137** [comment]
Thanks for pointing this out, Fergus.

Unfortunately, this is to do with the API that we use to search for spatial boundary information. We use [geonames](https://secure.geonames.org/) and just go by what they return to us. We found out a while ago that their bounding box for the UK is rubbish. Great Britain is better but obviously wouldn't include Ireland. 

Without moving to another provider I can't see a way around this for now.

**Comment by BethanPerkins** [comment]
Hi Fergus, thanks for this. As Tom said it's actually a geonames issue: https://www.geonames.org/2635167/united-kingdom-of-great-britain-and-northern-ireland.html

![image](https://user-images.githubusercontent.com/7328717/99821746-521ae280-2b4a-11eb-91db-3865ab03917a.png)

You can see the map by clicking on the map-pointer icon. It does look very odd. The easterly bound seems to be defined by Cyprus, I'm not sure what's defining the southerly bound.

Would using "Great Britain" (this excludes Northern Ireland) work for you instead? This has the bounds that you'd expect.

**Comment by fmcclean** [comment]
Thanks, I thought this was probably the case. My data covers the entire of the UK so Great Britain isn't really appropriate. The only solution I can see is allowing geojson files containing extent to be uploaded with the data. This would also solve other issues with geonames not being appropriate for specifying spatial extent precisely. Definitely not a priority but worth thinking about at some point.

**Comment by roseDickinson** [comment]
We have added an alternative to using Geonames in - specifying a geojson manually
