### ISSUE TITLE
Show warning when switching workflow steps without saving

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#56]
If you select a different workflow step after editing some fields, your edits are not saved and there is no warning. A warning asking something like "Are you sure you don't want to apply your changes?" before switching steps would be helpful.

**Comment by tg137** [comment]
I have created a ticket for this but we might have a better long-term solution which would mitigate the need for "committing" each change and instead implementing some undo functionality to rollback changes as you go.

We might end up getting round to the nicer implementation before getting round to the pop-up. 

https://jira.dafni.rl.ac.uk/browse/CORE-1768

**Comment by roseDickinson** [comment]
We've changed up the way that workflow step content is saved - it is now saved on making a change rather than requiring "apply changes" to be pressed. As of v4.0.0
