### ISSUE TITLE
Make dataset paths from definition file available in docker environment

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#6]

**Comment by jiphex** [comment]
Would you be able to explain a little more what you mean here @fmcclean?

**Comment by fmcclean** [comment]
At the moment, the paths that datasets are mounted at need to be specified in two places - once in the model definition file and once in the script which reads the data. I was suggesting that it might be better to have a name for each input dataset and then expose the path of that dataset as an environment variable to the container. Thinking about it further though, I'm not sure it makes much difference either way. You can close this if you like.

**Comment by BethanPerkins** [comment]
Closing this in response to @fmcclean last comment
