### ISSUE TITLE
Display model version on workflow status page

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#60]
This is required to be able to tell which version of a model generated an output dataset

**Comment by roseDickinson** [comment]
I've created [CORE-1661](https://jira.dafni.rl.ac.uk/browse/CORE-1661) to add this, I think changing the name of the Model into a link to the metadata for the specific version of the Model used is the best way to accomplish this. How does that sound?

**Comment by fmcclean** [comment]
Sounds ok, I would suggest having the version message underneath the model name so you don't need to navigate to a different page.

**Comment by tg137** [comment]
This was implemented as part of version 1.16
