### ISSUE TITLE
Add "required" option to model_definition_input_env

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#64]
The model definition schema should provide the option to set environment variables as not required in the same way as dataslots (with a boolean `required` option). This is necessary to allow input parameters to be optional. 

https://docs.secure.dafni.rl.ac.uk/docs/reference/model-definition-reference/#model_definition_input_env

**Comment by tg137** [comment]
Thanks Fergus, now linked to internal DAFNI issue: https://jira.dafni.rl.ac.uk/browse/CORE-663

**Comment by roseDickinson** [comment]
This was added in v2.6.0 of DAFNI last month
