### ISSUE TITLE
When setting data inputs, I can open multiple 'browser' windows

### ISSUE THREAD

**Issue by Craig-Robson** [dafnifacility/user-feedback#65]
If more than data input (dataslot) for a model, I can open the dataset browser window for each dataslot simultaneously

**Comment by roseDickinson** [comment]
Hi Craig, thanks for reporting this. As you can probably imagine this isn't intended functionality, I've created a bug in our backlog ([CORE-1731](https://jira.dafni.rl.ac.uk/browse/CORE-1731)) to address it.

**Comment by tg137** [comment]
This was fixed as part of the 1.16 release.
