### ISSUE TITLE
Access to documentation

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#68]
It's not very obvious how to get to the documentation. I suggest converting the question mark in the top right corner to be a link to the documentation pages.

**Comment by tg137** [comment]
We currently have an internal ticket against this (https://jira.dafni.rl.ac.uk/browse/CORE-1096). Rather than linking directly from the question mark, we're going to add a link to the docs as an additional section in the bar that appears.

Thanks for the reminder!

**Comment by BethanPerkins** [comment]
We've updated the platform to include a link to the help docs from the Question Mark symbol in release 2.1.0. Also included social media links, marketing website information and a link to this issue tracker along with the pre-existing support email.
