### ISSUE TITLE
Boolean input env documentation

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#69]
It's not clear how boolean type environment variables are handled. I'm assuming a tick box appears in the UI and they are exposed as "True" or "False" strings? Could do with some documentation [here](https://docs.secure.dafni.rl.ac.uk/docs/reference/model-definition-reference/#model_definition_input_env).

**Comment by tg137** [comment]
You're correct in your assumption but I agree the docs aren't clear. 

I've captured this internally here: https://jira.dafni.rl.ac.uk/browse/CORE-1769

**Comment by BethanPerkins** [comment]
This information has been added to the docs in release 2.1.0. Link is here: https://docs.secure.dafni.rl.ac.uk/docs/reference/model-definition-reference/#model_definition_input_env
