### ISSUE TITLE
Validate dataset IDs when uploading definition file

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#7]

**Comment by roseDickinson** [comment]
We currently have a task for this [CORE-799](https://jira.dafni.rl.ac.uk/browse/CORE-799) (DAFNI internal link) I've made a note of it so we can discuss in our next planning meeting when to work on this feature as it is relatively simple to add.

**Comment by BethanPerkins** [comment]
Ticket resolved in DAFNI release v1.11.0 (10 November 2020). Closing this issue.
