### ISSUE TITLE
Delete model version warning should reference version

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#71]
The warning that appears when deleting a model version shows the message `Do you really want to delete model X` when what I would expect to see is `Do you really want to delete version Y of model X`. From the current message, it seems as if all versions of the model would be deleted when this is not the case.

**Comment by elenaheister** [comment]
Thanks for reporting! Recorded as JIRA ticket [CORE-1786](https://jira.dafni.rl.ac.uk/browse/CORE-1786), will get that sorted today.

**Comment by BethanPerkins** [comment]
Released in DAFNI version 2.0.0
