### ISSUE TITLE
Workflow documentation missing

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#73]
As far as I can tell, there is no documentation about creating or executing workflows. This might be helpful for anyone new to the platform.

**Comment by tg137** [comment]
Yeah, we recognised this as a gap in the docs a while ago. We've captured it already in existing internal ticket https://jira.dafni.rl.ac.uk/browse/CORE-802

It's been in our backlog for quite a while but definitely a valuable thing to add.

**Comment by tg137** [comment]
We have added extensive workflow documentation in v3.0.0
