### ISSUE TITLE
Dataslots leaking between models when creating a workflow

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#74]
To reproduce this, switch quickly between steps in a workflow:

![DAFNI Facility](https://user-images.githubusercontent.com/17356802/111450629-7eb1c600-8708-11eb-977a-1081779e141d.gif)

**Comment by fmcclean** [comment]
I'm also seeing this behaviour when viewing workflow instances. The speed of switching steps does not seem to be relevant. 

![DAFNI Facility (1)](https://user-images.githubusercontent.com/17356802/111626426-e722a500-87e5-11eb-9cb5-fe2ad7686e58.gif)

**Comment by fmcclean** [comment]
I am still seeing this behaviour and it's quite confusing.

**Comment by roseDickinson** [comment]
This issue should be resolved with the new Workflow builder in v4.0.0
