### ISSUE TITLE
Link from datasets to workflow instances is now broken

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#75]
The old URL was like:

https://facility.secure.dafni.rl.ac.uk/workflows/instances/b7d938ef-3650-4f1b-a6be-a1d1cb2cb9f9

With the new release, this should be like:

https://facility.secure.dafni.rl.ac.uk/workflows/instance?id=b7d938ef-3650-4f1b-a6be-a1d1cb2cb9f9

But it hasn't been updated in the link on published datasets.

**Comment by BethanPerkins** [comment]
Hi - yes, we spotted this in the last release testing, it will involve a metadata update for old workflow datasets. Captured in [CORE-1798](https://jira.dafni.rl.ac.uk/browse/CORE-1798)

**Comment by roseDickinson** [comment]
I've just released a hotfix to fix the link injection for any new Datasets created from Workflows but as Bethan says a metadata update needs to be performed for old Workflow Datasets.

**Comment by BethanPerkins** [comment]
Second ticket created for metadata update in old workflow output datasets: [CORE-1799](https://jira.dafni.rl.ac.uk/browse/CORE-1799)

**Comment by roseDickinson** [comment]
Hi Fergus, we ended up taking a different route with the fix for this -> we've added a redirect so the old links in datasets will still work. This fix is now live.
