### ISSUE TITLE
Allow definition file to be pulled from GitHub repo

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#8]
Potential for automatic updating on push

**Comment by jiphex** [comment]
One way we've considered making model upload work (which might also be related to #4) is to figure out a way to have [Github actions](https://github.com/features/actions) automatically build and publish model versions from public GitHub (model) repositories.

I'm fairly sure this would be possible right now with some effort, although until we complete some upcoming authentication work the way that the action would authenticate against DAFNI would be a little clunky.

The process would be to use the standard Github "checkout" and "docker build" actions to build a docker image, then it could be saved and pushed to the public-facing (but currently undocumented externally) DAFNI API for model upload

**Comment by tomalrussell** [comment]
I'm here for this one too - in my mind it fits with the public facing API and possibly command line tool or SDK to enable dataset publishing as well as model publishing from CI or automated processes. I'd be happy to help figure out and document a slightly clunky process if the right way to do it is going to be stable for a bit.

**Comment by BethanPerkins** [comment]
Captured in ticket [CORE-1406](https://jira.dafni.rl.ac.uk/browse/CORE-1406) (DAFNI Internal)

**Comment by fmcclean** [comment]
Model upload GitHub Action is now available
