### ISSUE TITLE
Run a non-default model version

### ISSUE THREAD

**Issue by tomalrussell** [dafnifacility/user-feedback#81]
Given a model with multiple versions, I should be able to specify which model version to use in a workflow.

**Comment by tg137** [comment]
Thanks for this Tom.

The work for this has been in our backlog for a while, it's definitely something we want to enable.

The internal ticket is https://jira.dafni.rl.ac.uk/browse/CORE-283

**Comment by tomalrussell** [comment]
Cool - to give a couple of more motivational use cases:
- I'm building a new version of a model for DAFNI, I would like to run a couple of test workflows before making it the default.
- I'm working with a known-good version of a model for a particular analysis, I want to create new workflows with this specific version.

**Comment by tg137** [comment]
Thanks Tom, that's really useful.

**Comment by roseDickinson** [comment]
This was added in v4.1.0
