### ISSUE TITLE
Display model version when building workflow

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#82]
It is not clear at the moment which model version is being used when editing a model step in a workflow. This is important information and should be visible to the user.

**Comment by tg137** [comment]
Thanks Fergus, this is something we've been meaning to improve for a while. I've captured it in internal ticket https://jira.dafni.rl.ac.uk/browse/CORE-1976

**Comment by roseDickinson** [comment]
The version message and date of the version are now displayed underneath the Model name when creating a Workflow. This was added in v2.5.0.

![image](https://user-images.githubusercontent.com/47528557/125450386-ec696daf-1e43-4178-9e32-2e4b53f6232d.png)
