### ISSUE TITLE
Search by dataset ID what adding data to dataslot

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#84]
This would be a faster and easier method of finding data in some cases. Also, it would be useful to display the IDs in the `Select Datasets` popup.

**Comment by tg137** [comment]
Thanks for this.

Just to clarify, do you see this as being able to add the ID itself into the search bar and have the dataset pop up or rather a different option next to the dataslot allowing you to just type in the ID?

I think displaying the ID in the popup would be a good idea too.

I have captured this in https://jira.dafni.rl.ac.uk/browse/CORE-1988 and have linked back here so we can capture your clarification.

**Comment by fmcclean** [comment]
I think just typing the ID straight into the search box would be easiest but the other option would also work.

**Comment by tg137** [comment]
You can now search by version ID wherever you see the dataset catalogue.
