### ISSUE TITLE
Not possible to delete individual datasets from dataslots

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#85]
The only delete button that works is on the last dataset and this results in all datasets being removed. The expected behaviour here would be that each delete button only removes the corresponding dataset.

**Comment by tg137** [comment]
Ah, well spotted, sorry about that. I've put in a bug for this: https://jira.dafni.rl.ac.uk/browse/CORE-1989

**Comment by roseDickinson** [comment]
I've just released a hotfix that fixes this bug. Thanks for pointing this out Fergus!
