### ISSUE TITLE
Input parameters hidden on workflow status page

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#89]
All input parameters after the first 10 are not displayed on the workflow status page. This is quite a critical issue as there is no other way to access these in the UI.

**Comment by roseDickinson** [comment]
Thanks for raising this, I've created [CORE-2007](https://jira.dafni.rl.ac.uk/browse/CORE-2007) and am just releasing a hotfix for this now.

**Comment by roseDickinson** [comment]
Should be fixed now

**Comment by fmcclean** [comment]
Can confirm this is now fixed, thanks!
