### ISSUE TITLE
Workflow and model versioning

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#9]

**Comment by BethanPerkins** [comment]
Yes, this is a big one which is in progress. @roseDickinson and @tg137 are currently doing scoping work for this and how the models would then integrate with the rest of the platform.

**Comment by Craig-Robson** [comment]
Good to see this in progress. This will help with ease of use, especially as models and workflows develop through a project - being able to show data provenance i.e. the model and workflow version responsable for a result, is critical in a number of applications

**Comment by BethanPerkins** [comment]
Captured in tickets - 
- Model Versioning: [CORE-486](https://jira.dafni.rl.ac.uk/browse/CORE-486) (in progress at time of writing)
- Workflow Versioning: [CORE-271](https://jira.dafni.rl.ac.uk/browse/CORE-271)

**Comment by BethanPerkins** [comment]
Model versioning is now released. Ticket [CORE-486](https://jira.dafni.rl.ac.uk/browse/CORE-486) is Done.

**Comment by tg137** [comment]
Workflow versioning has now been released too in v3.0.0
