### ISSUE TITLE
Options display incorrectly if title not provided

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#92]
The schema for environment variable options says that `title` is not required but if it is not provided then instead of showing the names of the options, `[object Object]` is displayed. This issue also seems to affect the default value as it shows undefined rather than the specified value.

**Comment by roseDickinson** [comment]
Hi Fergus, good spot the title should be required in the schema, sorry about that. I'm not sure what you mean on the second point about default values, would you be able to provide a screenshot / link to a Workflow/Model page where the issue is visible?

**Comment by roseDickinson** [comment]
Created [CORE-2056](https://jira.dafni.rl.ac.uk/browse/CORE-2056) to track the first issue

**Comment by roseDickinson** [comment]
A hotfix has just been released that makes `title` a required field, so [CORE-2056](https://jira.dafni.rl.ac.uk/browse/CORE-2056) is complete.

If there is an extra issue with default values that this hasn't covered let us know.
