### ISSUE TITLE
Comments on Visualisation module

### ISSUE THREAD

**Issue by rendzina** [dafnifacility/user-feedback#94]
Having just been building and running the DAFNI test 'uk-climate-analysis' [model](https://github.com/dafnifacility/dafni-example-models/tree/master/uk-climate-analysis), a few comments, and suggested improvements to consider:

1. When you get to the visualisation, the environment is '/home/jovyan/' - the name 'jovyan' was confusing. It is a generic user name I believe, so could the 'user' be renamed to something more intuitive, eg. ‘dafni_runtime’ or ‘dafni_vis_user’ - something more self-explanatory?

2. I packaged up the python files in the example model (there are three of them). One is 'visualisation.py' and is for graphing the results 'post-run'. However, the container image loaded into DAFNI doesn't allow me to then access these other scripts - say I wanted to include a file like 'visualisation.ipynb' to load into a notebook. Could one have say a reserved folder 'visualisation' that is made visible in the visualisation tool for such files if they exist - eg like 'data/outputs' is? An alternative might be to pull in a GitHub repo of files into the visualisation...? This is about having a more complete 'end to end' offer from a model.

3. In visualisation (Mac/Safari 14.1.2) in Jupyter notebook I am getting an almost continuously repeating error/warning saying _‘Server connection error - A connection to the Jupyter server could not be established etc..’

4. In the DAFNI 'visualisations' interface I end up with a long list of defunct visualisations, which I don't want to see. I believe you retain these to support potential historical graphical outputs. However, from my perspective this is litter. I suggest change word from 'Decommission' to 'Remove' and then just hide these from my view. (after all I cannot 'recommission' one so why not hide from view)

5. It is somewhat misleading to use the term 'Edit' for updating workflows - one seems to have to create a NEW workflow ('Apply changes -> Create workflow'). Why can't I just 'save' my edits to the _same_ workflow? Also, it's a minor point, but the list of visualisations is given with a timestamp - but only showing the day (not time) of edit - so with lots having same name it is hard to be sure which is the latest one. Could the date shown have a html 'title' with the time of creation as a popup - or if room just show time too? Probably the same for other dated lists...workflows etc.

6. The '[How To](https://docs.secure.dafni.rl.ac.uk/docs/how-to/models/how-to-create-a-dafni-ready-model/)' documents section is great for preparing the docker files to load in. Can there be another short 'how to' on what you then need to do in DAFNI itself to receive, configure and run the model? Perhaps following the 'fibonacci-model' all the way through?

Thanks

**Comment by tg137** [comment]
Thanks for all the useful feedback Steve.

Here are the actions arising from each of your points:

1. Created new internal ticket: https://jira.dafni.rl.ac.uk/browse/CORE-2086
2. I think that visualisation templating will give you what you want here so it's already captured in an existing ticket.
3. That's already captured in internal ticket: https://jira.dafni.rl.ac.uk/browse/CORE-2001
4. Created new internal ticket: https://jira.dafni.rl.ac.uk/browse/CORE-2087
5. I'm hoping that this will be addressed in the upcoming release.
6. We have added extensive documentation in the upcoming release explaining how to use a model in a workflow so hopefully this will be addressed too.

**Comment by rendzina** [comment]
Great - many thanks for your responses
