### ISSUE TITLE
Add ability to create workflow based on an existing workflow

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#99]
The addition of workflow versioning now prevents existing workflows from being used as templates. It would save time to be able to create a new workflow based on an existing one.

**Comment by fmcclean** [comment]
This also applies to parameter sets

**Comment by roseDickinson** [comment]
You can now duplicate workflows in DAFNI, duplication of parameter sets has not yet been added but when you duplicate a workflow you can select to duplicate all existing parameter sets of that workflow

**Comment by roseDickinson** [comment]
Duplicating a parameter set was added in Feb 2024
